name: Issue assignment

on:
  issues:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: 'Auto-assign issue'
        env:
          VERSION_SUFFIX: ${{ secrets.SCCM_LOC_AUTO_ASSIGN_ISSUE_VERSION }}
        uses: pozil/auto-assign-issue@v$VERSION_SUFFIX
        with:
           repo-token: ${{ secrets.SCCM_LOC_AUTO_ASSIGN_ISSUE_TOKEN }}
           teams: sccm-loc
